[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "detect-private-key" },
  { id = "check-added-large-files" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
]
