apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
  name: canarypod-service-ssh
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app.kubernetes.io/managed-by: Helm
status:
  loadBalancer: {}