apiVersion: v1
kind: Pod
metadata:
  name: canarypod-attacker
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - name: canaryattacker
      image: "alpine:latest"
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]