Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-d73b04b0e696b0945 # Canary AMI ID, can be found in https://console.aws.amazon.com/ec2/home#AMICatalog:
      InstanceType: t3.micro
      Tags:
        - Key: Name
          Value: SRV-01 # Preferred Name of instsance
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId: subnet-283defa3eee4538 # Preferred Subnet, VPC is automatically selected from this.
          AssociatePublicIpAddress: false
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
